### PR TITLE
Link openal-soft statically.

### PR DESCRIPTION
**Pull request by zaquest**

### CODE REVIEW

**Comment by dnk777** [comment]
You have to maintain the correspondence between `priority` and module names array, that's pretty bad. You could have just iterated over the names array backwards, applying a shift of +1 to convert an index to a module num, but the implied shift is also not very good thing.

This is a pseudocode how it should be done in a robust fashion imo
```
static const struct {
	const char *name;
	int num;
} moduleDefs = {
	{ "openal_soft", 3 },
	{ "openal_system", 2 },
	{ "qf", 1 }
};


static const int numSoundModules = sizeof( module_defs ) / sizeof( module_defs[0] );

..........................................

const int specifiedModule = s_module->integer - 1;
assert( specifiedModule >= 0 && specifiedModule < numSoundModules );
if( !CL_SoundModule_Load( moduleDefs[specifiedModule].name, &import, verbose ) {
	int i;
	for( i = 0; i < numSoundModules; ++i ) {
		if( moduleDefs[i].num == specifiedModule ) {
			continue;
		}
		if( CL_SoundModule_Load( moduleDefs[i].name, &import, verbose ) {
			break;		
		}
	}
	if( i == numSoundModules ) {
		if( verbose ) {
			Com_Printf( "Couldn't load a sound module\n" );
			Com_Printf( "------------------------------------\n" );
		}
		Mem_FreePool( &cl_soundmodulepool );
		se = NULL;
		return;
	}
	Cvar_ForceSet( "s_module", va( "%i", moduleDefs[i].num ) );
}
```

**Comment by ghost** [comment]
Please, I am begging you not to do that, that is portability nightmare. It is better to link to openal-soft installed at system. I have to patch openal-soft to make it work at *BSD systems. The same goes to AngelScript, I have no choice but to manually patch it.

**Comment by zaquest** [comment]
This is an addition, not a replacement. If there's no sound module for the staticallly linked openal-soft it will fallback to the module that uses system's openal, and then to the older qf sound module. One could skip building openal-soft sound module entirely and just use the other two.

**Comment by ghost** [comment]
@zaquest that order is ridiculous, if I have AngelScript installed system-wide, it tries to build AngelScript in Git submodule anyway.

**Comment by dnk777** [comment]
Sorry I do not understand you @mazocomp. If I got it right ... we don't use a system-wide AngelScript distribution but the one from the submodule for various reasons. Please also note that binaries built using the current master are not compatible with vanilla Warsow 2.1 assets (which is the version currently available for public). Refer to the code in the "SDK" published on the Warsow website if you are trying to build binaries for that game version.

**Comment by zaquest** [comment]
@mazocomp I have no idea about AngelScript. As about OpenAL, in general I would've agreed with you, but since warsow loads it's modules dynamically, and we still keep the module that loads OpenAL dynamically it's not as harmful as usually. And yes, it will try to build OpenAL-soft module anyway, unless you patch the CMakeFile.

**Comment by ghost** [comment]
@zaquest what is the advantage of including and compiling those libraries in the repository when it is easy to link them both statically and dynamically when they are already installed system-wide? Usually those libraries won't compile and/or run without OS-specific patches made by porters in the world other than Windows, OSX, Android and Linux anyway. For example, porting AngelScript to OpenBSD was a hell to me.

**Comment by ghost** [comment]
And the patches I made to it are not upstreamed!

**Comment by dnk777** [comment]
The OpenAL SOFT implementation ought to be linked statically. This way we can provide a sound module that has a reliable support of HRTF and EFX effects and that is important for both competitive and casual play. In addition, static linking of OpenAL soft ensures that it has the right "revision". That library is great but is seemingly maintained by a single person, and glitches sometimes occur, and sound output differs from commit to commit. We had a moment of panic when the effects output has started to sound completely different compared to as it used to be. All effect parameters had to undergo tweaking again. We want to ensure that the sound output is the same as it is intended to be by developers on every consumer machine. I can name the only use-case when using a system AL is better: using a Creative sound hardware on Windows, where effects/positioning are supposed to be of higher quality.

**Comment by dnk777** [comment]
I can also name a reason for having an own copy of AngelScript code. We may think of adding a JIT support for it, and JIT is distributed only in a source code form and probably assumes a fixed AngelScript version.

**Comment by ghost** [comment]
@dnk777 if AngelScript follows semver, it shouldn't break API/ABI compatibility until its major number is raised, so if you've written JIT for AngelScript 2.29.0, it should work at AngelScript 2.32.0, but not vice-versa, because raising a minor number means there is new functionality.

**Comment by dnk777** [comment]
@mazocomp I frankly do not know the reasons behind that design choice as it was made by the original repository author (and this is our fork for things that we (who happen to maintain the game nowadays) think ought to be changed). However we are not going to change anything related to AngelScript now at this stage as we planning a new release. If there are any changes now they are in parts I'm 100% confident as these parts were in scope of mine interest during development.

You miss the fact there is something more "sinister" is going to be done, namely putting prebuilt binaries of CEF/Chromium in a separate subrepo.

**Pull request merged**
