### PR TITLE
First step to support FreeBSD, OpenBSD, NetBSD, DragonFly BSD and Solaris

### PR DESCRIPTION
**Pull request by ghost**
Tested at OpenBSD. libref_gl.so fails to load.

### CODE REVIEW

**Comment by ghost** [comment]
@dnk777 any chances Warsow will run at architectures other than i386 and amd64?

**Comment by dnk777** [comment]
There's nothing that prevents compiling and running at other architectures (aside from some parts that imply LE byte order just because we didn't bother with it). However this stuff is out of scope for me. Moreover i have *temporarily disabled* macOS builds because they were quite annoying during development and i have currently no intention to support it (given the fact i know only 2 persons who have been using macOS version of the game during last 3 years including me at some stage).

**Comment by ghost** [comment]
@dnk777 I don't think supporting FreeBSD, NetBSD, OpenBSD and DragonFly BSD will be problematic (I don't even know why FreeBSD support was dropped), but I need help to fix Warsow at run-time. Do you have any ideas why it rejects to use libref_gl.so? How can I debug this? Also how can I make it look for data files in /usr/local/share/warsow? What should I do with modules_xx.pk3 file? Does Warsow binary at OpenBSD try to load Linux's libraries in that file? If yes, what should I do with that?

**Comment by dnk777** [comment]
There are multiple binaries built, not only the game executables (that are invoked via the shell script) but also the entire contents of the `libs` subdirectory and also two game libraries `libgame_*.so`, `libcgame_*.so` that should usually be put in the `modules*` pak. All paks that correspond to the game version are currently expected to have `22` prefix. Game libraries can be loaded just from `basewsw` subdirectory if `modules*` pak is removed.

**Comment by ghost** [comment]
@dnk777 in my case they are named libgame.so and libcgame.so, I am surprised CMake didn't append _x86_64 or _amd64 (I only read part of CMakeList.txt files, so I am not aware of any additional variables). Also I see you don't know how to fix other runtime problems?

**Comment by ghost** [comment]
@dnk777 about data files: is there a way I can build them myself so I won't need to download tarball with Windows, macOS and Linux binaries?

**Comment by dnk777** [comment]
There is a separate minimal repository for a quick start https://github.com/Warsow/warsow-root

**Comment by ghost** [comment]
@dnk777 are you ok with patches which will just name all libraries and executables at OSes other than Windows, macOS, Linux and Android without suffixes like _freebsd_x86_64? I am asking this because I am a porter and I rely on ports systems, not official binaries. I expect qfusion games will be available at FreeBSD ports, OpenBSD ports, pkgsrc and Ravenports.

**Comment by dnk777** [comment]
I am not interested in accepting anything from a person who has reportedly used cheats online multiple times (destroying user experience of other players this way) ... especially related to this minor topic that has nothing with actual challenges in the game development.

**Comment by dnk777** [comment]
To clarify the situation as there might be misunderstanding. We knew what to expect from this person very well: https://github.com/Warsow/qfusion/pull/30. That time we were very polite even all these demands are ridiculous. Lately we have discovered this is a cheater as well, using cheats in a shameless fashion (so pretending being a maintainer is like a pedo asking to be a kindergarden manager). Having accepted this pull request, aggressive demands to remove newly added features that were supposed to make the game better, like licensed proprietary sounds, would've followed. This person speaks like we owe him something solely on the basis the source code of the engine is here at Github. This is some kind of "jesus freaks".

**Comment by XutXtuX** [comment]
**https://github.com/OrangeGrayCyan/warsow/blob/master/README.md**

@dnk777 You are lying, take a look in that README

**Comment by dnk777** [comment]
1) We need a fixed OpenAL SOFT version available out-of-box for reasons well-described there https://github.com/Warsow/qfusion/pull/30.
2) We're looking forward to use Chromium UI as this is the only way to make a good and maintainable UI with few efforts, and that is vital for the continuation of the game development. So far prebuilt CEF/Chromium binaries are a preferrable way of working with it (trying to assemble it from the source code directly is much more painful).
3) A person that did repeatedly some sinister things, namely using cheats therefore destroying user experience of other players and violating terms of service has no right to put their conditions on the direction of the game development.
4) The fact the source code is here at Github does not mean that third parties can put their conditions on the direction of the game development.

**Pull request closed without merging**
